export const FORM_EMAIL = "email"
export const FORM_PW = "password"
export const FORM_PW_CONFIRM = "password-confirm"
export const FORM_NICKNAME = "nickname"
export const FORM_COMMENT = "comment"
export const FORM_RATING = "rating"
